### ISSUE TITLE
证书上传成功后，证书列表里没有显示，是只能使用真实的证书？自签的不行吗？

### ISSUE THREAD

**Issue by dong2590** [Tencent/nohost#11]
使用的环境
```
OS: centos7
node：v12.13.1
nohost: 0.4.14
```

**Comment by avwo** [comment]
可能格式不正确，尽量用正式，如果自定义的可以直接用nohost。

**Comment by dong2590** [comment]
> 可能格式不正确，尽量用正式，如果自定义的可以直接用nohost自带的。

正式的拿不到 😭 ，nohost 自带在哪呢？貌似没有文档说明，如何使用呢？

**Comment by avwo** [comment]
跟whistle一样下载，然后在环境里面配置 pattern enable://capture

**Comment by aogg** [comment]
whistle下载的crt无法作为nginx的https证书使用，这个能兼容下吗  @avwo

**Comment by avwo** [comment]
为什么不能用？

**Comment by aogg** [comment]
<img width="788" alt="image" src="https://github.com/Tencent/nohost/assets/8998031/197c0dd3-f74b-47ec-b5c8-2e2db02992e3">

用文件夹里nohost/.whistle/certs里的crt和key就会这样，已经信任过证书了，而且whistle界面里https里“Download RootCA”没有key文件可以下载

@avwo
