### ISSUE TITLE
请问nohost中，在一个账号中能使用@引用另外一个账号已经配置好的规则环境吗？ 我在本地建立了2个账号，尝试一个账号用@符号引另一个账号配好的环境，一直无法成功

### ISSUE THREAD

**Issue by tmacMcGrady** [Tencent/nohost#113]

**Comment by avwo** [comment]
截图看下你是怎么配的（issue 的标题尽量言简意赅，详细描述放内容，不然看起来很费劲）

**Comment by tmacMcGrady** [comment]
![image](https://user-images.githubusercontent.com/13829581/150754860-bfe964fc-c164-4912-9c16-e7a84edc1326.png)
在t2这个账号下使用@t3引用了t3的已经配好的环境
![image](https://user-images.githubusercontent.com/13829581/150755642-d0d2d10d-4002-410b-b656-ed392111bddb.png)
这个t3配置好的环境

**Comment by avwo** [comment]
不要放 `Default` ，`Default` 里面的规则是账号公共规则，没法被其它账号直接引用，你可以试试 `@t3/yy`

**Comment by tmacMcGrady** [comment]
好的 谢谢大佬
