### ISSUE TITLE
nohost中可以动态获取到当前机器ip直接代理到指定域名吗？

### ISSUE THREAD

**Issue by JM-Master** [Tencent/nohost#134]
本地开发时，不同开发者本地服务ip不同，可以共用一个账号进行动态获取ip代理到example.com，文档没看出来关于这方面的详细说明

**Comment by avwo** [comment]
当前机器指 Nohost 运行的服务器，还是用户的机器？

**Comment by JM-Master** [comment]
用户的

**Comment by avwo** [comment]
https://wproxy.org/whistle/data.html 看下后面的模板字符串

**Comment by JM-Master** [comment]
这个我设置了，在whistle本地时可以拿到clientIp的，但我希望在nohost里面设置的时候拿这个clientIp，但时拿不到，写死ip就可以，但写死ip了，别人再用我这个配置就走的我的ip地址了

**Comment by avwo** [comment]
> 可以共用一个账号进行动态获取ip代理到example.com
这个是什么意思？

**Comment by JM-Master** [comment]
182.219.204.45:3006 https://example.com
https://example.com ${clientIp}
我是想多人共用这个配置 ，比如a再本地跑了个前端服务，那https://example.com就指向他的本地ip，我用的话，就指向我的ip

**Comment by avwo** [comment]
试试
``` txt
https://example.com/ http://`${clientIp}`
```

**Comment by JM-Master** [comment]
https://example/ http://`${clientIp}:3000`

这样跑通了~感谢大佬= =
