### ISSUE TITLE
使用vite启动的项目配置nohost域名绑定无法正常访问

### ISSUE THREAD

**Issue by klaaay** [Tencent/nohost#138]
vite配置
```ts
    server: {
      port: 3007,
      host: '0.0.0.0',
      open: true,
      https: true,
      hmr: {
        host: 'x.x.x.x',
      },
      },
    },
```
nohost的域名绑定配置
https://xxxxxxxxxxxx.com/ https://`${clientIp}:3007

想问下这边是因为vite的server配置有什么问题，还是nohost这边本身会有什么限制的

**Comment by avwo** [comment]
https://`${clientIp}:3007 改成 host://`${clientIp}:3007

**Comment by klaaay** [comment]
大佬可以了，感谢，另外想问下为什么这么改就能用的

**Comment by klaaay** [comment]
> https://`${clientIp}:3007 改成 host://`${clientIp}:3007

大佬可以了，感谢，另外想问下为什么这么改就能用的

**Comment by avwo** [comment]
vite 限制了请求头` host`

**Comment by klaaay** [comment]
大佬还有个奇怪的问题我写
^a.xx/cf/*** https://b.xx/cf/$1 在最外层是起效果的
![image](https://user-images.githubusercontent.com/29458506/163123928-40ffe962-6694-4bec-a492-da4d5376a952.png)
写在内部
![image](https://user-images.githubusercontent.com/29458506/163124132-159bb086-db15-412e-a9d2-2b7cf4b82e8d.png)
就不能正常访问这是为什么的

**Comment by avwo** [comment]
请求过去了没，这种配置可简化 `^a.xx/cf/*** https://b.xx/cf/$1` -> `a.xx/cf/ https://b.xx/cf/`

**Comment by klaaay** [comment]
> 请求过去了没，这种配置可简化 `^a.xx/cf/*** https://b.xx/cf/$1` -> `a.xx/cf/ https://b.xx/cf/`

这边从https://`${clientIp}:3000` -> host://`${clientIp}:3000` 之后放在内部可以了
