### ISSUE TITLE
小程序无法使用，没有注入小圆点，无法切换环境

### ISSUE THREAD

**Issue by alipay404** [Tencent/nohost#15]

**Comment by longyiyiyu** [comment]
官方暂时没出，要用可以自己写一个，也比较快，抓web的nohost相关的接口请求：

- 查询接口
- 设置接口

然后实现一个小程序组件，除了接口逻辑之外，ui可以参考的地方不多，自己写也不难
另外也可以直接参考 web 小圆点组件的源代码：
https://github.com/nohosts/nohost/blob/master/src/button/index.js

**Comment by alipay404** [comment]
> 官方暂时没出，要用可以自己写一个，也比较快，抓web的nohost相关的接口请求：
> 
> * 查询接口
> * 设置接口
> 
> 然后实现一个小程序组件，除了接口逻辑之外，ui可以参考的地方不多，自己写也不难
> 另外也可以直接参考 web 小圆点组件的源代码：
> https://github.com/nohosts/nohost/blob/master/src/button/index.js

但是小程序没有所谓的请求地址，怎么实现动态注入呢

**Comment by avwo** [comment]
要构建的时候注入，并设置一些开关
