### ISSUE TITLE
能否单独设置默认环境？

### ISSUE THREAD

**Issue by haovei** [Tencent/nohost#150]
现状：A 用户切换环境 env1，B 用户切换 env2，A 用户刷新页面后，环境变 env2.

能否做个默认环境的设置开关，关闭后，多个用户切环境不干扰默认值？

**Comment by avwo** [comment]
用户请求的 client ip 是不是不唯一？

**Comment by haovei** [comment]
> 用户请求的 client ip 是不是不唯一？

不唯一。A测试业务1，B测试业务2，同一局域网内也都有干扰。代理服务是部署到外网的，这个有影响么？

**Comment by haovei** [comment]
> 用户请求的 client ip 是不是不唯一？

感谢提醒，找到问题了。代理服务是部署到外网的，同一局域网内对外是一个 ip，所以才有干扰
