### ISSUE TITLE
Default 规则内通过 @userName/ruleName 导入不生效

### ISSUE THREAD

**Issue by gongpeione** [Tencent/nohost#155]
nohost 版本：1.4.6
whistle 版本：2.9.22

我们在使用过程中发现在一个用户的 Default 规则内通过 @userName/ruleName 导入对应的规则似乎是不生效的，请教一下这个逻辑是 By Design 么？

例：
**用户 A**
- Default 规则
  - @template/defaultTpl
 
**用户 template**
- defaultTpl 规则
  - www.github.com resHeaders://a=1

**Comment by avwo** [comment]
Default 不支持这个特性

**Comment by gongpeione** [comment]
> Default 不支持这个特性

了解了，感谢
