### ISSUE TITLE
想引入nohost，遇到如下问题

### ISSUE THREAD

**Issue by Geek-S** [Tencent/nohost#157]
- 加群（加微信多次未通过）
- 希望部署在公网，但是目前出现被刷问题（使用proxyauth插件，PC端正常，手机端异常）

**Comment by avwo** [comment]
扫二维码加群：
![image](https://user-images.githubusercontent.com/11450939/186338647-5d5756b9-d9f2-4852-9826-480913fc210a.png)

**Comment by Geek-S** [comment]
已加，谢谢
