### ISSUE TITLE
接口无法代理

### ISSUE THREAD

**Issue by xiangfengsu** [Tencent/nohost#160]
版本:
nohost : 1.5.7
问题:
css,js可以代理，但接口无法代理,抓包试图只能看到css,js等文件的代理，接口无法看到,但如果只用whistle 来代理就可以成功
 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/9291534/194753626-78bcdd7d-8086-4fcb-b727-d92acdada6f5.png">
<img width="880" alt="image" src="https://user-images.githubusercontent.com/9291534/194753676-52348ba1-285b-4de2-8f64-fd49364ed89b.png">
下面图片是whistle 抓包截图
<img width="903" alt="image" src="https://user-images.githubusercontent.com/9291534/194753764-202df6c0-fede-4f14-b7c1-8109a61314eb.png">

微信二维码过期了，可以贴个新的吗

**Comment by avwo** [comment]
入口配置了页面的域名没

**Comment by xiangfengsu** [comment]
> 入口配置了页面的域名没

配置了，页面上环境切换的小圆圈都出来了，感觉就是接口代理不成功，我测试了代理html 也是成功的
<img width="500" alt="image" src="https://user-images.githubusercontent.com/9291534/194754689-8f02a146-4f27-4647-ae93-5ee7e75e9e62.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/9291534/194754705-8888fd3e-00ff-45bc-905c-9cdd0c40a624.png">

**Comment by avwo** [comment]
有配置什么规则吗

**Comment by xiangfengsu** [comment]
> 有配置什么规则吗

就是接口的代理 比如  api.xxx.com  api2.xxx.com 这样的规则，关键是我用whistle 都可以成功，配置一模一样

**Comment by avwo** [comment]
请求没过来会不会是缓存的原因，用 Chrome 抓包看下请求有没有转到代理

**Comment by xiangfengsu** [comment]
> 请求没过来会不会是缓存的原因，用 Chrome 抓包看下请求有没有转到代理

我把nohost 重新启动了，代理成功了，新问题来了，抓包显示的都是GET 请求，没有POST，虽然POST的接口已经代理转发成功了，可是看不到

**Comment by avwo** [comment]
晚点我看看

**Comment by xiangfengsu** [comment]
> 晚点我看看

微信群加不了，方便给个二维码不？

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/194756316-5658ca10-2f58-464c-b38f-7fe51e3a270d.png)

**Comment by xiangfengsu** [comment]
> 晚点我看看

好奇怪啊，我创建了2个环境，a环境，b环境，页面上切换a环境，代理成功，切换b环境，代理的接口还是a环境的，切换正式环境还是走的a环境的代理, 怎么切换都不生效了

**Comment by avwo** [comment]
看下overview 里面 client ip 或 client id 是否会自动变化

**Comment by xiangfengsu** [comment]
client id 没有变化，我本地开启了vpn ，我的client ip 是127.0.0.1 ,client Port 不通的请求，值都不一样

**Comment by avwo** [comment]
有 client id 吗

**Comment by xiangfengsu** [comment]
有的，client id 没有变化

**Comment by xiangfengsu** [comment]
@avwo 我在本地启动nohost 环境切换生效了，部署到服务器上又不行了，比如a,b,c 3个环境，无论怎么切换都是a环境的配置, b,c 无法生效，关键还是无法抓取到接口的请求，无法看到rule 配置内容

**Comment by avwo** [comment]
导出抓包我看下

**Comment by xiangfengsu** [comment]
> 

导出的报没有接口数据，接口没有转发代理成功

**Comment by xiangfengsu** [comment]
已经可以了，谢谢
