### ISSUE TITLE
weinre端口获取

### ISSUE THREAD

**Issue by answer-huang** [Tencent/nohost#163]
<script async="" charset="utf8" src="https://hello.com/.whistle-path.5b6af7b9884e1165/weinre.30017/target/target-script-min.js#hello"></script>

这个 30017 的值看了下源码是用的端口的值, 有什么办法通过 api 获取到吗?

我想在另一个系统里面自己对 html 注入上面这段 script

**Comment by avwo** [comment]
这个端口不是固定的，如果需要用 weinre，可以通过设置代理的正常方式处理

**Comment by answer-huang** [comment]
> 可以通过设置代理的正常方式处理

目前想要实现的功能是某一个用户反馈有问题, 我们会直接给一个二维码用户, 扫描后, 打开的网页是已经注入了 weinre 了的页面.
如果需要设置代理, 对于用户来说就比较麻烦了.

看样子需要实现这个功能, 只能独立部署下 weinre 了.

**Comment by avwo** [comment]
这是因为 nohost 下面每个账号的端口是随机的，如果单独部署 whistle 就没这个问题。

**Comment by answer-huang** [comment]
> 这是因为 nohost 下面每个账号的端口是随机的，如果单独部署 whistle 就没这个问题。

OK, 昨天还想到宿主机上找到进程, 把端口上报给 server, 但是又跟账号没法关联起来, 后来就放弃了.
