### ISSUE TITLE
自定义注入页面小圆点样式

### ISSUE THREAD

**Issue by xiangfengsu** [Tencent/nohost#164]
1:注入页面小圆点样式可以修改吗？
<img width="250" alt="image" src="https://user-images.githubusercontent.com/9291534/199874774-1e3bf8d3-6995-44c7-bdc4-6c8b1e625787.png">
2:选择账号的时候可以配置只能看到哪些账号吗？我看现在是全部账号，比如a,b,c,   某个用户打开只能看到b账号，其他都看不到，这个可以配置吗？
<img width="397" alt="image" src="https://user-images.githubusercontent.com/9291534/199874939-6ee50bb7-6dae-4795-8b3f-67fb23881701.png">

**Comment by avwo** [comment]
暂不支持，用户获取账号列表是没有登录态无法鉴权，不过后续可以加上这个功能
