### ISSUE TITLE
nohost 配置入口疑问

### ISSUE THREAD

**Issue by xiangfengsu** [Tencent/nohost#165]
1:配置规则后一定要把规则的中域名写在配置入口中吗?

比如：
规则:
www.abc.com   www.xxx.com
通过SwitchyOmega 配置nohost代理IP 

那一定要在nohost 的规则页面中配置
-www.abc.com
否则代理就失效了
问，是我使用姿势有问题，还是就是这么操作的，如果必须这些操作，那我每次加入新的rule ,都必须要把对应的域名都要在配置页面中设置一下，比如 新增 www.new.com ，那么配置页面也要加入   -www.new.com ,那是不是很麻烦

**Comment by avwo** [comment]
这个相当于白名单，白名单里面的请求才会转到 nohost

**Comment by xiangfengsu** [comment]
> 这个相当于白名单，白名单里面的请求才会转到 nohost

能不能配置个*啥的，默认全走，不然加规则就要在白名单里配置，感觉有点麻烦

**Comment by avwo** [comment]
可以，动手试下就知道
