### ISSUE TITLE
nohost 内使用的 weinre2 库是否支持三方独立使用

### ISSUE THREAD

**Issue by answer-huang** [Tencent/nohost#166]
你好, nohsot 里面的 weinre2 库貌似是做了一些修改, 请问我是否能单独运行这个库 ? 本地安装了下, 貌似不能直接运行.

**Comment by avwo** [comment]
不建议这么用

**Comment by answer-huang** [comment]
> 不建议这么用

是因为做了魔改么. 官方的库不维护了, 用官方的库运行, 注入失败率很高.  nohost 使用的 weinre2 感觉好些, 但是端口不固定, 没法集成到系统里.

**Comment by avwo** [comment]
对，修复一些bug，你可以单独运行 whistle，端口是稳定的
