### ISSUE TITLE
nohost使用下划线_，直接做反向代理服务器失效

### ISSUE THREAD

**Issue by momopig** [Tencent/nohost#169]
你好，我以前在whistle使用下划线_，然后直接在浏览器使用http://127.0.0.1:8899/_/api，能够被规则正常匹配。但是使用nohost的whistle却不能，请问为何？

**Comment by avwo** [comment]
nohost 暂不支持这种用法，后续可以加上

**Comment by momopig** [comment]
> nohost 暂不支持这种用法，后续可以加上

建议快点同步哈～如果支持反向代理，理论上可以让webpack devServer代理到nohost，其他成员都不用配置浏览器代理，想验证一下

**Comment by avwo** [comment]
更新下 nohost
