### ISSUE TITLE
socket connect timeout

### ISSUE THREAD

**Issue by linliyuan** [Tencent/nohost#175]
使用nohosts client进行安装：
配置了入口规则如下：
![image](https://user-images.githubusercontent.com/37769385/207494671-f4bb94fd-f64f-4353-a76e-960988461432.png)
其他没有配置，直接访问百度，报错如下：
![image](https://user-images.githubusercontent.com/37769385/207494770-010ccdc2-ce48-4712-8ad3-84751510b787.png)
请求需要加什么配置项之类的吗？

**Comment by avwo** [comment]
请求不通，你先在自己的电脑上试试

**Comment by linliyuan** [comment]
> 请求不通，你先在自己的电脑上试试

是在自己电脑打的nohosts server，用的是也是自己电脑的做client，网络也是正常的，看上去是代理到nohosts上了吧，但是报了错误，要怎么排查呢？

**Comment by linliyuan** [comment]
后续重启电脑后恢复了正常
