### ISSUE TITLE
websocket 消息双向通信转发

### ISSUE THREAD

**Issue by answer-huang** [Tencent/nohost#176]
![image](https://user-images.githubusercontent.com/1219398/207496672-2985214a-36f3-42dc-8e1c-6a18cc3cf7a6.png)

@avwo , 你好, 请问通过插件能实现这样的功能么:

nohost 作为一个 proxy,  我们 App 和  devtools 中的 websocket 都连接到 nohost, 通过 nohost 来转发 websocket 消息.

**Comment by p2227** [comment]
nohost本来就可以连接websocket
