### ISSUE TITLE
是否支持http、https以外的协议

### ISSUE THREAD

**Issue by linliyuan** [Tencent/nohost#179]
请问一下：
1. 是否能直接代理ip访问MySQL数据库，达到类似修改本地hosts的效果？
2. 本地程序进行请求的时候能进行ip代理吗？
在win10上对两者做了测试，都没有成功，nohosts能达到以上场景吗？还是只能在浏览器使用？
返回结果是一段js：
![image](https://user-images.githubusercontent.com/37769385/208465239-a2a50b3b-e1d8-430c-bfef-c207718860ab.png)

**Comment by linliyuan** [comment]
> 支持的，单人使用建议用 Whistle：https://github.com/avwo/whistle

现在想在团队中使用，使用场景比较复杂，不止是简单的http、https这些浏览器web场景，还想兼容本地代码程序、软件连接数据库等tcp连接场景，统一管理不同环境的host，从而实现一键切换，所以需要像nohost这样的远程配置。统一配置后，使用者用本地工具进行切换就行。这种的话在nohost上可以实现吗？

**Comment by avwo** [comment]
可以，只要tcp都支持

**Comment by linliyuan** [comment]
> 可以，只要tcp都支持

像上面我截图的那个go程序要怎么进行调整呢？如何才能够直接返回

**Comment by avwo** [comment]
参考：https://juejin.cn/post/6844903592625700871

**Comment by linliyuan** [comment]
> 参考：https://juejin.cn/post/6844903592625700871

这种还是基于Whistle的场景吧，而且要修改原始代码。想知道如果是使用nohost，最好能直接用 https://github.com/nohosts/client 这个客户端（方便非技术人员切换环境）的情况呢？能否在不调整原始代码的情况下完成？

**Comment by avwo** [comment]
和 nohost 通用的，我们 node 服务就这么处理，只是增加几行代码侵入性还可接受，如果不想侵入代码自己网上搜看看
