### ISSUE TITLE
请求微信号多次无法进群

### ISSUE THREAD

**Issue by linliyuan** [Tencent/nohost#183]
是否加群微信号已经没有维护了？
请求了多次无法进入

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/215430762-2f969383-016d-45b3-b2a8-86eace46443a.png)

**Comment by answer-huang** [comment]
@avwo 麻烦再给一个二维码, 这个过期了. 谢谢.

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/221452833-e3df9953-7d8f-48e0-a976-d4d317af3175.png)

**Comment by avwo** [comment]
![image](https://github.com/Tencent/nohost/assets/11450939/8f111629-36e1-4f76-abb1-325a1c13564e)
