### ISSUE TITLE
baseDir 绝对路径(如 /data/.nohost )配置不生效

### ISSUE THREAD

**Issue by sunkeysun** [Tencent/nohost#192]
如配置 baseDir: /data/.nohost ，则实际会将数据文件生成到 `${homedir()}/.nohost/data/.nohost` 下
源码文件
https://github.com/Tencent/nohost/blob/master/lib/whistle.js
<img width="570" alt="image" src="https://user-images.githubusercontent.com/23015246/228219622-3d6e7660-3fa5-4afe-8c64-26adc068f667.png">

**Comment by avwo** [comment]
可以通过环境变 `NOHOST_PATH` 设置存储根目录，baseDir 只是用来改目录名称
