### ISSUE TITLE
通过SwitchyOmega直接代理到Nginx转发的nohost服务器访问不通

### ISSUE THREAD

**Issue by xwLyc** [Tencent/nohost#20]
公司服务器只暴露80端口，我在服务器启动nohost服务端口是9999
比如服务器域名是 abc.com，当我访问 abc.com时，Nginx转发到 proxy_pass http://127.0.0.1:9999;
当我直接访问abc.com是可以显示环境列表选择页面，abc.com/admin.html 也能访问。

然后通过SwitchyOmega配置代理如下，使用该情景模式时，任意网站都无法访问，要怎么配置...
![image](https://user-images.githubusercontent.com/14286912/92429317-1f588380-f1c4-11ea-8c7b-48dd1382ea9b.png)

**Comment by avwo** [comment]
尽量直接访问，不要经过nginx，如果需要经过nginx参考下这篇文章：https://zhuanlan.zhihu.com/p/81880837

**Comment by xwLyc** [comment]
刚看了文章描述，如果需要经过nginx，是不是只能先在本机whistle通过internal-proxy 到Nginx服务器才可以，这样的话，对测试人员就不是特别友好了😂

**Comment by avwo** [comment]
nginx不支持http proxy，只能直接请求，再通过反向代理到whistle

**Comment by xwLyc** [comment]
好的，万分感谢~

**Comment by mingyec** [comment]
@avwo 大佬，同遇到这个问题，现在有什么新的解决方案么

**Comment by avwo** [comment]
通过 `浏览器 > SwitchyOmega > Whistle > Nohost` 访问试试：https://nohost.pro/docs/quickstart
