### ISSUE TITLE
这里的证书和key如何配置呀

### ISSUE THREAD

**Issue by chengcheng2023git** [Tencent/nohost#200]
请问大佬，这个证书和key是如何配置呀，比如通过app抓包，证书是指的从app连接nohost代理下载证书上传吗？那key又是什么呢？辛苦告知下如何配置，感谢

**Comment by avwo** [comment]
可以从你们服务器上获取，找运维要

**Comment by chengcheng2023git** [comment]
![image](https://github.com/Tencent/nohost/assets/139936702/2272c395-22ed-4c50-982f-9b3c93695c79)
上传证书会有个cert和key,上传的是cert吧，但我上传会提示证书和key不匹配，请问这里如何上传呢
