### ISSUE TITLE
端口暴露失败

### ISSUE THREAD

**Issue by Thinker-Mars** [Tencent/nohost#31]
大家好，我在阿里云ecs启动了nohost服务，监听8181端口，并且像往常一样开放了此端口，但是奇怪的是，在公网telnet这个端口并不通，想问下大家是怎么操作的？（已尝试过变更端口及重启防火墙）
备注：
1、nohost服务是正常启动的
![image](https://user-images.githubusercontent.com/42603916/102457584-ed39a600-407d-11eb-8f35-540a69770bbb.png)
2、端口已暴露
![image](https://user-images.githubusercontent.com/42603916/102457649-0b9fa180-407e-11eb-8450-d9b8c292ad30.png)

**Comment by avwo** [comment]
试试 `n2 restart -p "serverIp:8181"` ，其中 `severIp` 是暴露到公网到ip

**Comment by Thinker-Mars** [comment]
> 试试 `n2 restart -p "serverIp:8181"` ，其中 `severIp` 是暴露到公网到ip

你好，输出如下：
![image](https://user-images.githubusercontent.com/42603916/102463330-ef9ffe00-4085-11eb-9fff-ad6f780f346a.png)
上面生成的这个访问地址很诡异...

**Comment by avwo** [comment]
if confit能否看到这个公网ip

**Comment by buxuku** [comment]
和Thinker-Mars一样的问题,通过`ifconfig`是看不到公网IP的.我尝试通过nginx转发也无法访问

**Comment by Thinker-Mars** [comment]
> 和Thinker-Mars一样的问题,�通过`ifconfig`是看不到公网IP的.我尝试通过nginx转发也无法访问

兄弟你是团队想用这个吗？在公司内网试下？云服务器似乎不行..

**Comment by avwo** [comment]
Nohost 默认是根据 client ip 来关联选择的环境，如果是外网接入可能会出现多个机器共用一个 client ip 的情况，需要在 Nohost 上再加一层网关（如：Nginx）设置请求头 `x-whistle-client-id` 来替代 client ip。
