### ISSUE TITLE
【应用示例】基于 Nohost 的开发方式

### ISSUE THREAD

**Issue by avwo** [Tencent/nohost#4]
### 安装Node
1. 下载及安装Node：[Node官网](https://nodejs.org/en/)

### 安装工具
1. 安装whistle及所需插件：
    ``` sh
    npm i -g whistle whistle.nohost-xxx
    ```
    Mac 或 Linux 可能需要加 `sudo`：
    ``` sh
    sudo npm i -g whistle whistle.nohost-xxx
    ```

    其中，`whistle.nohost-xxx` 用于切换nohost环境的whistle插件（实现参考：[https://github.com/nohosts/whistle.nohost-imweb](https://github.com/nohosts/whistle.nohost-imweb)），主要用于选择后台测试环境，前端无需本地配置后台环境，具体操作看后面介绍。
2. 启动whistle：
    ``` sh
    w2 start
    ```
	> Mac是如果用brew安装Node可能会出现命令找不到问题，手动配下path，或者网上找下解决方案
3. 配置代理：
    - 安装Chrome插件：[SwitchyOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif)
    - 配置代理参数（whistle默认端口为 `8899`）：
      ![配置whistle代理](https://user-images.githubusercontent.com/11450939/50470421-56d0cd80-09eb-11e9-97b9-351684e8be56.png)
      ![选中whistle代理](https://user-images.githubusercontent.com/11450939/50470448-72d46f00-09eb-11e9-9341-529d6bb4e3b0.png)

4. 打开whistle界面：[http://local.whistlejs.com](http://local.whistlejs.com)
5. 安装whislte根证书：https://wproxy.org/whistle/webui/https.html

上述操作只在第一次开发项目需要安装，后面最多只需在**重启电脑时**启动下whistle即可：`w2 start`
### 开始工作
1. 检出项目代码（以 `agency-react` 为例）：
    ``` sh
    git clone http://git.test.com/xxx/agency-react.git
    ```
2. 检出代码后，进入项目根目录安装依赖：
    ``` sh
    tnpm i
    ```
3. 一键配置本地映射规则：
    ``` sh
    w2 add
    ```
4. 启动本地构建：
    ``` sh
    npm run dev
    ```
5. 打开 `whistle界面 > Plugins > nohostenv插件界面` 选择对应后台测试环境：
    ![配置本地环境](https://user-images.githubusercontent.com/11450939/50476079-ba65f580-0a01-11e9-8598-20d47f80954f.gif)

所有项目的本地映射规则都放在项目的 `.whistle.js` 文件中，并通过 `w2 add` 命令自动设置到whistle，无需手动配置项目的本地环境；所有公共环境都在nohost上配好，前端无需配置后台环境，后台也无需配置前端环境，产品测试无需配置任何环境。

### 页面调试
1. 注入 `vConsole` 或 `eruda` 可以用插件：https://github.com/whistle-plugins/whistle.inspect
2. 查看指定页面错误及页面console输出的信息：http://wproxy.org/whistle/webui/log.html
3. 通过weinre查看修改指定页面的DOM节点：http://wproxy.org/whistle/webui/weinre.html

更多功能参考：[https://github.com/avwo/whistle](https://github.com/avwo/whistle)

**Comment by Miiskye** [comment]
你好 .whistle.js文件有示例吗，具体是怎么配置账号和环境的呢

**Comment by avwo** [comment]
https://wproxy.org/whistle/cli.html
