### ISSUE TITLE
【增强】左上角的选择框太短，名字长的环境显示不全

### ISSUE THREAD

**Issue by xdc0209** [Tencent/nohost#41]
问题：
![image](https://user-images.githubusercontent.com/3997527/104889081-9db20700-59a8-11eb-868d-36ee2fabe6f0.png)

希望改进点：
1. 增加选择框的宽度。
2. 当前选择的内容可以复制出来。

**Comment by avwo** [comment]
更新下 nohost `npm i -g @nohost/server` 后重启 `n2 restart`
