### ISSUE TITLE
Default规则会覆盖具体环境规则

### ISSUE THREAD

**Issue by btboy12** [Tencent/nohost#44]
比如在default里配置规则 www.example.com host://1.1.1.1
![image](https://user-images.githubusercontent.com/12553837/105953453-2833ee00-60ae-11eb-98f4-ea9b4bbec6a2.png)

在下面一个具体环境《test host》里配置规则 www.example.com host://2.2.2.2
![image](https://user-images.githubusercontent.com/12553837/105953487-371aa080-60ae-11eb-9377-117fd6199ca7.png)

期望效果：在《test host》环境下将 www.example.com 解析为 2.2.2.2
实际效果：在《test host》环境下将 www.example.com 解析成了 1.1.1.1 。配置被default覆盖了
![image](https://user-images.githubusercontent.com/12553837/105953622-6d582000-60ae-11eb-830d-0d588ef6aac0.png)

**Comment by WzFFzW** [comment]
规则优先级问题导致，会再下一个版本进行迭代解决

**Comment by avwo** [comment]
更新下 nohost `npm i -g @nohost/server` 后重启 `n2 restart`
