### ISSUE TITLE
多用户是什么意思？

### ISSUE THREAD

**Issue by liruiqing** [Tencent/nohost#45]
现在我们搭建了一个nohost，并在后台创建了多个用户，但是 手机测试绑定了服务器代理之后，一台设备切了用户，或环境，其他设备也跟着切换了，这是多用户吗？

**Comment by avwo** [comment]
你们是部署在外网吧，环境是跟访问的clientId关联的

**Comment by liruiqing** [comment]
我们都是内网环境，内网ip

**Comment by avwo** [comment]
抓包看下 client ip 是不是都长一样

**Comment by liruiqing** [comment]
嗯嗯，我们正在试，我们的2台设备链接的是同一个华为的路由，可能ip是相同的

**Comment by 493326889** [comment]
多用户是指 团队每个人可以有一个独立的空间，自己可以创建多个测试环境。
且每个环境的实时抓包、whistle规则都是单独隔离的

**Comment by liruiqing** [comment]
已解决

**Comment by xiaowanzixll** [comment]
> 已解决

你好，想问一下你是怎么解决的？

**Comment by xiaowanzixll** [comment]
> 已解决
搭建了一个nohost，并在后台创建了多个用户，但是 手机测试绑定了服务器代理之后，一台设备切了用户，或环境，其他设备也跟着切换了------想问一下怎么让其它设备可以不用跟着切换？怎么做到的？望回复

**Comment by xiaowanzixll** [comment]
> 你们是部署在外网吧，环境是跟访问的clientId关联的

我们是部署在内网，在后台创建了多个用户，但是 手机测试绑定了服务器代理之后，一台设备切了用户，或环境，其他设备也跟着切换了。有没有办法可以让其它设备不跟着切？比如多用户切换到自己的用户，别人切换不影响自己的环境跟着切换？

**Comment by avwo** [comment]
nohost 默认是通过 clientIp 来区分用户的，手机访问代理服务器前还会经过哪些服务？
