### ISSUE TITLE
文档里面说的前端开发和其他人员使用问题

### ISSUE THREAD

**Issue by liruiqing** [Tencent/nohost#49]
问题1：按照说明改了ip和端口，但是怎么能跟服务器上搭建的 nohost关联上？
其他人员
非开发人员尽量使用客户端、APP、或通过外网转发的方式，减少他们的接入成本，如何打包客户端参考：https://github.com/nohosts/client；手机等同后台开发的配置方式。

问题2：如何在 Whistle 上配置远程规则？ 找了好久，找不到在哪里配置。
直接在 Whistle 上配置远程规则
@http://nohost.imweb.io:8080/whistle.nohost/cgi-bin/plugin-rules

问题3：本地Whistle插件装上之后，连不上nohost，而且无法抓包，关了插件才能抓包？
【强烈推荐】 集成 Whistle 插件，具体参考：https://github.com/nohosts/whistle.nohost-imweb/blob/master/dev.md

**Comment by wangzemin2017** [comment]
可以加交流群问问
![image](https://user-images.githubusercontent.com/29788452/106610307-94788b00-65a1-11eb-955f-ea7a854a1c30.png)
