### ISSUE TITLE
部署nohost无法进入管理员页面

### ISSUE THREAD

**Issue by Jer-X** [Tencent/nohost#50]
nohost版本： 0.6.4
node版本:：v12.18.2
whistle版本：2.6.6

触发步骤：
1. 按上手流程安装nohost程序，执行n2 start
2. 访问http://127.0.0.1:8080/admin.html#system/administrator
3. 无法显示相关页面
![image](https://user-images.githubusercontent.com/19970845/107186010-71752d80-6a1e-11eb-8ecf-4ed8edbb1d8b.png)

相关页面请求头信息

General
Request URL: http://127.0.0.1:8080/admin.html
Referrer Policy: strict-origin-when-cross-origin

Response Headers
Connection: keep-alive
Content-Length: 87
Content-Type: text/html; charset=utf8
Date: Mon, 08 Feb 2021 07:00:44 GMT
WWW-Authenticate: Basic realm=User Login

Request Headers:
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: max-age=0
Connection: keep-alive
Cookie: _ga=GA1.1.1914157490.1597197896; Hm_lvt_d214947968792b839fd669a4decaaffc=1605233845
Host: 127.0.0.1:8080
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36

初步排查结果：
1. /admin.html的路由需要做登陆校验，这个的登陆校验过不了
![image](https://user-images.githubusercontent.com/19970845/107186632-9ddd7980-6a1f-11eb-861c-d0bcdc85c047.png)
![image](https://user-images.githubusercontent.com/19970845/107186663-a766e180-6a1f-11eb-9523-fa87e3340f46.png)

成功结果：
1. 把登陆校验去掉之后就能成功显示页面
![image](https://user-images.githubusercontent.com/19970845/107187119-73d88700-6a20-11eb-9bcd-c956b232203a.png)

**Comment by avwo** [comment]
这个鉴权不能去掉，没有弹出登录框吗，什么浏览器？

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/108452165-025fca80-72a3-11eb-9287-a826791c9a2f.png)
