### ISSUE TITLE
《账号默认规则》会覆盖各账号自己配置的Default环境配置

### ISSUE THREAD

**Issue by btboy12** [Tencent/nohost#52]
比如在《账号默认规则》配置:
www.example.com host://1.1.1.1
![image](https://user-images.githubusercontent.com/12553837/108670111-478d3200-7519-11eb-87ce-c947db4a67b3.png)

在一个具体账号的《test》里的《Default》环境配置:
www.example.com host://2.2.2.2
![image](https://user-images.githubusercontent.com/12553837/108670132-5247c700-7519-11eb-9c1c-847ab7e4e840.png)

期望表现：www.example.com 解析到  2.2.2.2
实际表现：www.example.com 解析到了 1.1.1.1
![image](https://user-images.githubusercontent.com/12553837/108670211-7905fd80-7519-11eb-9c8e-b6becfa0d160.png)

**Comment by avwo** [comment]
确实会有这个问题，下个版本解决。
PS: `www.example.com host://2.2.2.2` 可以简写成 `www.example.com 2.2.2.2`

**Comment by avwo** [comment]
更新下nohost
