### ISSUE TITLE
whistle远程规则配置 @http://imwebtest.test.com:8080/whistle.nohost/cgi-bin/plugin-rules，为什么看不到小圆点？

### ISSUE THREAD

**Issue by gottayan** [Tencent/nohost#56]

**Comment by avwo** [comment]
`http://imwebtest.test.com:8080/whistle.nohost/cgi-bin/plugin-rules` 里面的 `imwebtest.test.com:8080` 要改成你自己的域名(IP)和端口，还要安装证书及配置入口规则，详见文档：https://nohost.pro/docs/

**Comment by gottayan** [comment]
> `http://imwebtest.test.com:8080/whistle.nohost/cgi-bin/plugin-rules` 里面的 `imwebtest.test.com:8080` 要改成你自己的域名(IP)和端口，还要安装证书及配置入口规则，详见文档：https://nohost.pro/docs/

不经过本地whistle远程规则，直接连接就是可以的。

**Comment by gottayan** [comment]
> > `http://imwebtest.test.com:8080/whistle.nohost/cgi-bin/plugin-rules` 里面的 `imwebtest.test.com:8080` 要改成你自己的域名(IP)和端口，还要安装证书及配置入口规则，详见文档：https://nohost.pro/docs/
> 
> 不经过本地whistle远程规则，直接连接就是可以的。

域名和端口都是配置成功的，而且nohost也抓取到请求了，只是看不到小圆点。

**Comment by avwo** [comment]
抓包截图我看下

**Comment by gottayan** [comment]
> 抓包截图我看下

![Uploading image.png…]()

**Comment by gottayan** [comment]
> 抓包截图我看下

<img width="792" alt="企业微信截图_9dc29fbc-5eea-43ea-ad07-82fcb12d48ef" src="https://user-images.githubusercontent.com/23098167/112289451-4b070b00-8cc9-11eb-83a4-071d5bb1463a.png">

**Comment by avwo** [comment]
这个配了吗
![image](https://user-images.githubusercontent.com/11450939/112292636-3ed07d00-8ccc-11eb-8e45-4eba317c778d.png)

**Comment by gottayan** [comment]
配了的 就是直接访问nohost就有 但是经过本地whistle远程规则就没有了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: avenwu ***@***.***&gt;
发送时间: 2021年3月24日 18:11
收件人: Tencent/nohost ***@***.***&gt;
抄送: gottayan ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Tencent/nohost] whistle远程规则配置 @http://imwebtest.test.com:8080/whistle.nohost/cgi-bin/plugin-rules，为什么看不到小圆点？ (#56)





 
这个配了吗

**Comment by avwo** [comment]
打开页面源码看下有没有注入js

**Comment by gottayan** [comment]
> 打开页面源码看下有没有注入js
http://m.baidu.com/...whistle-path.5b6af7b9884e1165...///whistle.nohost/button.js
请求404

**Comment by avwo** [comment]
看下这个请求是不是被拦截了

**Comment by gottayan** [comment]
> 看下这个请求是不是被拦截了

![企业微信截图_21f964da-0d7d-4906-9fbe-b316ce46c77d](https://user-images.githubusercontent.com/23098167/112414975-fe214400-8d5d-11eb-9f25-cbfa28d542ad.png)
代理都无法抓到这个请求

**Comment by avwo** [comment]
Whistle 是最新版本吗，还有配其它规则么？

**Comment by gottayan** [comment]
> Whistle 是最新版本吗，还有配其它规则么？

w2: 2.6.8
node: 14.15.1
其他规则
*.baidu.com whistle.inspect://eruda
*.taobao.com whistle.inspect://eruda

**Comment by avwo** [comment]
Whistle 上可以抓到这个请求吗

**Comment by gottayan** [comment]
就没抓到js的请求



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: avenwu ***@***.***&gt;
发送时间: 2021年3月25日 11:54
收件人: Tencent/nohost ***@***.***&gt;
抄送: gottayan ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Tencent/nohost] whistle远程规则配置 @http://imwebtest.test.com:8080/whistle.nohost/cgi-bin/plugin-rules，为什么看不到小圆点？ (#56)

**Comment by avwo** [comment]
wireshark 查下这个请求去哪了

**Comment by gottayan** [comment]
> wireshark 查下这个请求去哪了

你那边本地试了可以接入吗

**Comment by avwo** [comment]
我这边 ok，入口规则配了 `m.baidu.com` 了吗，你们是哪个公司？

**Comment by avwo** [comment]
更新下whistle 和nohost
