### ISSUE TITLE
手机抓包扫二维码大部分情况都绑不上，手机提示设置成功，但实际没成功

### ISSUE THREAD

**Issue by liangdouer** [Tencent/nohost#60]
手机抓包扫二维码大部分情况都绑不上，手机提示设置成功，但实际没成功。

**Comment by liangdouer** [comment]
![image](https://user-images.githubusercontent.com/81422337/112633744-b3deb680-8e74-11eb-9528-35d8f7321497.png)

**Comment by WzFFzW** [comment]
下个版本修复
