### ISSUE TITLE
【体验】Rules支持快速回到目标rule

### ISSUE THREAD

**Issue by hmhao** [Tencent/nohost#74]
在顶部栏搜索【目标rule】名称后，Rules列表会选中并打开【目标rule】
![image](https://user-images.githubusercontent.com/5087008/124412662-97122300-dd81-11eb-9f28-61b34ebc37bf.png)

如果这时查看了其他rule项，则无法快速返回到【目标rule】。
如果Rules列表有很多项的话，则需要在众多的列表项中找回【目标rule】，过程非常痛苦。

期望优化一下这个交互，提供一键切回目标rule的能力

**Comment by ZSI2017** [comment]
@hmhao  目前在搜索过程中，页面不会刷新，只有点击搜索下拉列表中的一项，才会刷新页面，没看懂最后说的rules列表很多项无法找回的情况？

**Comment by hmhao** [comment]
切换到其他rule后，在顶部搜索中重新选择【目标rule】，并没有切换回【目标rule】
![image](https://user-images.githubusercontent.com/5087008/124430542-e1a39780-dda1-11eb-9699-a51b7c9cc2ff.png)
