### ISSUE TITLE
环境选择支持倒排，方便选择最近创建的环境

### ISSUE THREAD

**Issue by LeoMamz** [Tencent/nohost#81]
环境选择支持倒排，方便选择最近创建的环境
![image](https://user-images.githubusercontent.com/44152171/135094837-675bf940-4e60-4acf-bf69-ea7d06afae15.png)

**Comment by avwo** [comment]
重新安装 `@nohost/server`，创建规则新增了一个 `+Top` 按钮，可以直接将规则加到最前面：

![image](https://user-images.githubusercontent.com/11450939/135199474-3d736805-075a-4a34-87a5-6477a212b7a5.png)
