### ISSUE TITLE
每个账号下的环境支持文件夹形式的管理

### ISSUE THREAD

**Issue by LeoMamz** [Tencent/nohost#82]
例如，每个服务一个文件夹，然后测试、灰度、正式各一个文件夹，然后文件夹下才是具体某个环境。
或者说基于场景划分文件夹，然后再是具体的环境。
![image](https://user-images.githubusercontent.com/44152171/135095140-cf5df911-3b33-4c4d-b615-5cbd5bcf00bf.png)

**Comment by avwo** [comment]
Duplicate of https://github.com/Tencent/nohost/issues/48
