### ISSUE TITLE
主程你的项目还是一如既往的文档缺漏啊

### ISSUE THREAD

**Issue by aogg** [Tencent/nohost#85]

**Comment by aogg** [comment]
Usage: n2 <command> [options]


  Commands:

    install     Install the plugin
    uninstall   Uninstall the plugin
    run         Start a front service
    start       Start a background service
    stop        Stop current background service
    restart     Restart current background service
    help        Display help information

  Options:

    -h, --help                   output usage information
    -p, --port [proxyPort]       set the listening port or host:port (8080 by default)
    -n, --username [username]    set the username to admin
    -w, --password [password]    set the password to admin
    -o, --nohostDomain [domain]  set the nohost domain (as: nohost.imweb.io,xxx.yyy.com)
    -a, --account <account>      set the account for installing the plugin (all accounts by default)
    -s, --storage <host:port>    set the host:port of server to save the request data
    -M, --mode [mode]            set the starting mode (as: prod)
    -V, --version                output the version number

**Comment by avwo** [comment]
hhh 我的问题，可以先看看：https://nohost.pro/，有问题提 issue，或参与完善文档 https://github.com/Tencent/nohost/tree/master/docs
