### ISSUE TITLE
nohost支持whistle的 x-forward-for启动配置

### ISSUE THREAD

**Issue by kenzung** [Tencent/nohost#87]
![image](https://user-images.githubusercontent.com/6317307/141444898-7e096bad-12d4-4ba0-81fd-8d91a39dbacc.png)
如图，希望nohost增加whistle启动配置 x-forward-for

**Comment by avwo** [comment]
这个是默认设置的，如果要禁用可以通过 `pattern disable://clientIp`

**Comment by avwo** [comment]
更新一下nohost
